name: Windows-RDP-6-Hours
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      - name: Start Cloudflare Tunnel
        run: |
          Invoke-WebRequest https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cf.exe
          Start-Process ./cf.exe -ArgumentList "tunnel --url rdp://localhost:3389"
      - name: 6 Hour Keep Alive
        run: |
          echo "Machine is running... Link check karo logs mein!"
          sleep 21600
